### PR TITLE
add support for Rails 5

### PR DESCRIPTION
**Pull request by tierra**
This commit also drops support for:
- Rails 3
- Ruby 1.9
- Ruby 2.0

### CODE REVIEW

**Comment by tierra** [comment]
@codekitchen Could I get a review of the changes here when you have some time? It doesn't appear like there's really any changes necessary for Rails 5 support (using the same logic as Rails 4).

You might recall that this is a dependency of inst-jobs, which I'm hoping to test out for Rails 5 support after this as well.

**Comment by maneframe** [comment]
The alias_method_chain in rails4.rb is deprecated in Rails 5, so while we're here we should probably replace it with a Module and prepend it

**Comment by codekitchen** [comment]
Agreed, since we're dropping ruby 1.9 support let's move to a prepend.

**Comment by tierra** [comment]
Sounds good, I'll clean this up some more.

**Comment by tierra** [comment]
Prepend is in place, with a bit more cleanup of Rails 3 code removal from spec_helper.

**Comment by codekitchen** [comment]
Looks good to me, I'll merge and cut a new gem

**Pull request merged**
